language: php

services:
  - mongodb

php :
  - 5.5
  - 5.6
  
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install

notifications:
  slack: mosaiqo:4VdHFaCyZ8Sbwp3R1Iof1uaa