language: php

services:
  - mongodb

php :
  - 5.5
  - 5.6
  - hhvm

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install